wandb_version: 1

__is_set:
  desc: null
  value:
    wallet.name: true
    wallet.hotkey: true
    subtensor.network: true
    logging.trace: true
model_path:
  desc: null
  value: ~/model.pth
subtensor:
  desc: null
  value:
    __is_set: {}
    network: local
    chain_endpoint: wss://entrypoint-finney.opentensor.ai:443
    _mock: false
logging:
  desc: null
  value:
    __is_set: {}
    debug: false
    trace: true
    record_log: false
    logging_dir: ~/.bittensor/miners
wallet:
  desc: null
  value:
    __is_set: {}
    name: '2'
    hotkey: '1'
    path: ~/.bittensor/wallets/
axon:
  desc: null
  value:
    __is_set: {}
    port: 8091
    ip: '[::]'
    external_port: null
    external_ip: null
    max_workers: 10
config:
  desc: null
  value: null
strict:
  desc: null
  value: false
no_version_checking:
  desc: null
  value: false
no_prompt:
  desc: null
  value: false
uid:
  desc: null
  value: 237
hotkey:
  desc: null
  value: 5EZGRiRtTuxipeSq1vgwZgkwu4kdj7Lh1U6Yu7ZerRMQkE19
run_name:
  desc: null
  value: 237-BQH9XSLBHZ
_wandb:
  desc: null
  value:
    python_version: 3.9.10
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698962166.926191
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      3:
      - 3
      - 13
      - 16
      - 23
      4: 3.9.10
      5: 0.15.10
      6: 4.35.0
      8:
      - 5
